### ISSUE TITLE
Register operatefirst.cloud

### ISSUE THREAD

**Issue by quaid** [operate-first/community#102]
And have it redirect to operate-first.cloud.

Intention is to make the site more discoverable, and to turn the speaking URL into something easier done, i.e. saying "operate first dot cloud" becomes correct regardless of the listener putting in the "-".

- [x] register domainname with Google Domains
- [ ] configure Googgle Cloud DNS Zone and a pointer to the actual webserver
- [ ] deploy webserver to redirect to operate-first.cloud

**Comment by goern** [comment]
As we can not deploy a second CNAME with GitHub Pages, we need to deploy a dedicated webserver to send a HTTP redirect, see https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages

or does anyone have another idea?

@tumido @harshad16

**Comment by quaid** [comment]
> As we can not deploy a second CNAME with GitHub Pages, we need to deploy a dedicated webserver to send a HTTP redirect, see https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages
> 
> or does anyone have another idea?
> 
> @tumido @harshad16

If you don't have a way to spin this up, it may be the osci.io team has something they can bring over and/or add to the mix.

@mscherer I'm sure you have a process to do this, outside of the Op1st community cloud. But do you happen to have a container that does this role already that could be deployed into the community cloud?

**Comment by mscherer** [comment]
Yup, we have a server dedicated to that: https://gitlab.com/osci/community-cage-infra-ansible/-/blob/master/playbooks/tenants/osci/redirector.yml 

We do not have a container for that. It doesn't seems hard, that's just a webserver, the biggest issue being the TLS integration (not a big deal either, but there is no standard way for that AFAIK). 

As I am already late on others op1st task, I would rather suggest the easy way, eg, reuse osci infra, and later, a container would be a good "easyfix" for bootstrapping a community contributor.

So if the solution on the osci.io redirector is the chosen solution, the step are:
- add a A record poiting to 8.43.85.237 for the apex domain
- same for any subdomain
- ask me or @duck-rh to add the redirection

We have to use A record for the apex domain, per RFC. We can also add AAAA on top, I think, if we want to do IPv6.

**Comment by goern** [comment]
@mscherer please check `www.operatefirst.cloud` and `operatefirst.cloud`, from my side of the pond it looks good:

**Comment by mscherer** [comment]
Seems good, the redirection is in place.

**Comment by quaid** [comment]
Thanks folx, this works a charm.

I'm closing this one as complete, and opened #108 for what @mscherer suggested.
