### ISSUE TITLE
Naming proposal: Change project/community/cloud name to "Op1st"

### ISSUE THREAD

**Issue by quaid** [operate-first/community#104]
To differentiate between the general concept of Operate First  as defined in OpenInfra Labs, this proposal is to adopt the handy moniker Op1st for all references to the project, the community, and the community assets and services.

- Op1st community cloud
- Op1st community
- Op1st cluster in MOC
- Are you integrating your open source project into Op1st?
- How many contributors does Op1st have?
etc.

**Comment by quaid** [comment]
Where I am starting from is this problem statement:

> Since it is important and a given that _Operate First_ as a concept and an overarching methodology **MUST** be neutral on technologies and methods for it to be adopted by the ecosystem and have an effect ... 
> ... how do we differentiate between that neutral concept and the specific technologies and methods we adopt in this community without diluting the meaning and brand of "Operate First"?

In other words, when we call anything/everything in this OpenShift and GitOps/GitHub-using community "Operate First", we are _diluting our own brand_. We are confusing the meaning of Operate First and making it harder for ourselves to have the ecosystem-wide effect.

Yet, we are doing all this hard work for the intended effect of showing and proving that the Operate First concept and methodology actually work in practice, in the real world, with real workloads in a real production environment. It is equally important we connect this community with the Operate First brand and not dilute that brand.

So the goals are:
1. Connect with but don't dilute the Operate First brand,
2. Don't make our lives harder (for no good reason), and
3. Widen the tent of those who want to and can _operate first_ by giving them an "Operate First"-brand that can include them regardless of their relationship to our specific community technologies and methods.

As a slight-rough analogy, look at the Fedora Project and community, and their central output, Fedora Linux.

People use the word "Fedora" to mean any one of those, it's a common short hand. But when you think about it, the brand is "Fedora" and the brand being connected-with-but-not-diluted-by "Fedora" is the "Linux" brand.

In our situation, the "Operate First" brand is more analogous to "Linux" than it is to "Fedora". And until we can get the Operate First brand to have ecosystem reach the way the "upstream first" concept sort-of has, I believe we are looking for the fine line of "close but not too close" in branding for this community project.

The two just-close-enough ideas I've seen so far are:
1. "Op1st", spoken as "Op First"
2. "O1", spoken as "Oh One" (or "Oh First"?)

I wholeheartedly invite debate and other name ideas.
 
Two final thoughts;
- One of my mentors on branding @cdgrams (or was it Burney?) said, "A brand is a sponge." Since we get some say on the cellular structure of that sponge and first crack at filling the sponge, let's make it count.
- "Op1st" is a recursive pun, being the first operating community to run itself under the Operate First concept.

**Comment by billburnseh** [comment]
+1, I'd vote for Op1St since it's been used a lot already, to reflect on the example implemented to date.

**Comment by schwesig** [comment]
+1 Op1st, I like Op1st in general but especially compared to O1 | also following @billburnseh explanation
-1 O1

**Comment by schwesig** [comment]
/remove-lifecycle stale
i thought we already decided on that?
@billburnseh @quaid @tumido @goern ...

**Comment by quaid** [comment]
> Based on how active this issue is, I don't think the name change is a pressing issue to many people... 

This is an aside from the topic, but I think we should be careful when presuming activity on Issues and PRs is a sign of interest. Most people are not familiar with GitHub, git-based workflow, and how they are used to track discussions of ideas.

> I don't mind the change, I have a concern if it implies changing all the names, like domain name, DNS, documentation, github org, quay org, etc. I don't see the name change to justify the additional work.

Agree, this is a branding decision and not intended to affect domain names, classnames, quay.io, org names, etc.

(But we should grab a few domain names e.g. op1st.org and op1st.cloud as shorthand links.)

I'm going to finally propose this on the mailing list, which is where we need to make the final decision.

> /cc @durandom @goern @HumairAK

**Comment by Gregory-Pereira** [comment]
Not sure my input is worth much but I do like the idea. It helps to separate the concept and implementation through the difference in naming convention. In anycase I am wondering what the status of this is @quaid, and if this is still progressing what are the next steps. If not let me know so I can close this issue.
/remove-lifecycle stale

**Comment by quaid** [comment]
So this idea ran into a wall of "no thanks" on the mailing list, I got a little discouraged, and didn't get back to it.

I think people want to keep the full "Operate First" name, that's OK, but I also think we need a consistent way to abbreviate so we are driving toward clarity. I think the closing for this issue would be for me to go back to the mailing list and propose alternatively that we pick this as our formal abbreviation.

**Comment by goern** [comment]
is this all lower case "op1st" ?
