### ISSUE TITLE
Form the Website Updates (Spring 2022) WG

### ISSUE THREAD

**Issue by quaid** [operate-first/community#134]
Cross-functional WG to work through all the open issues, ideas, and discussions for making changes _right now_ to the website.

Goals:

- Improve messaging discovery
- Improve user experience
- Solve Community Handbook knot
- Create nucleus for future SIG Website

**Comment by jeremyeder** [comment]
I am curious if others would be interested in adding blog support to the op1st website?  We are thinking of adding some story-telling content from Red Hat SRE teams and are thinking it'd be great to host on the op1st website if it were possible.

**Comment by quaid** [comment]
> I am curious if others would be interested in adding blog support to the op1st website? We are thinking of adding some story-telling content from Red Hat SRE teams and are thinking it'd be great to host on the op1st website if it were possible.

Putting this note here that conversation on this topic is continuing at #24.
