### ISSUE TITLE
Operate First SIG-Community - student involvement

### ISSUE THREAD

**Issue by schwesig** [operate-first/community#136]
Heidi updated the Research Team on the progress with the Operate First SIG-Community.  She also mentioned opportunities/a need to engage students.  This felt potentially like something we could make Boston University students aware of via the Collaboratory.

The Collaboratory Core Planning Team meets once a week or so.  Would one of you like to join an upcoming meeting for 15 minutes to discuss options for engaging students this route?  

Here are the dates of the next few meetings (all EST)

3/17 @ 1.30-2.30 PM
3/24 @ 3-4 PM

**Comment by schwesig** [comment]
Quick update.  I had to cancel the March 10 Collab Core Team call.  The next two meetings where we could discuss this are 

March 17 @ 1:30 PM EST 
March 24 @ 3PM EST

**Comment by quaid** [comment]
@hpdempsey Can you let us know what the updated schedule is? Thanks

**Comment by quaid** [comment]
@schwesig @hpdempsey Can we look at the student coop onboarding and such to see where we can have a regularly-run section on community involvement?

The other perspective is to make sure all of the curriculum is saturated with the details and ethos of Open Collaboration.

/remove-lifecycle stale

**Comment by hpdempsey** [comment]
We can certainly do that as a regular part of onboarding for both interns and co-ops at Red Hat.  With BU's agreement, we could also offer it to students who are funded for their own student projects through the Red Hat Collaboratory awards at BU.  https://www.bu.edu/rhcollab/2022/04/14/red-hat-collaboratory-announces-2022-student-research-projects/

The curriculum effort is bigger, but we can work on that as a longer-term effort.
