### ISSUE TITLE
[SIG Community] List volunteers/members per SIG/SP/WG

### ISSUE THREAD

**Issue by schwesig** [operate-first/community#142]
Feb 24, 2022 | [[Op1st] SIG Community weekly call](https://www.google.com/calendar/event?eid=NTg0czUwdHVwNnZuMGg0ZG5vOTVoZGJxM21fMjAyMjAyMjRUMTgwMDAwWiB0c2Nod2VzaUByZWRoYXQuY29t)

Create a list of all member/volunteers/... for each team/group.

**Comment by schwesig** [comment]
should not be a one time thing, maybe create a .yaml file, automated process, ... at some point in time?

**Comment by schwesig** [comment]
```mermaid
  flowchart TB
    sig1 -- to be created --- wg1;
    sig1 -- to be created --- wg2;

    subgraph sig1[SIG Community]
      subgraph sig1chairs[Chairs]
        sig1chair1[quaid];
        sig1chair2[schwesig];
      end
      sig1member1[hpdempsey];
    end

    subgraph wg1[WG Website]
      subgraph wg1chairs[Chairs]
        wg1chair1[tbd];
      end
      wg1member1[hpdempsey];
    end

    subgraph wg2[WG Contrib_X Docs]
      subgraph wg2chairs[Chairs]
        wg2chair1[tbd];
      end
      wg2member1[hpdempsey];
    end
```

**Comment by hpdempsey** [comment]
Current volunteers for WG Website:   Marcel, Karsten, Stephanie, Bryan  (durandom, quaid, stefwrite, bryanmontalvan).  Will update if we get more after first meeting.

**Comment by quaid** [comment]
Hmm ...

It seems like this is something we could automate to pull out of `github://operate-first/common/blob/main/github-config.yaml`?

Then we are maintaining it all in one place.

We definitely want to have this in a friendly appearance in the User & Contributor Handbook for finding who is working on what in the projec.

**Comment by schwesig** [comment]
We for sure should!
This was just the start to at least have a basic idea.

Friendly appearance: automatically filled by the .yaml file?

**Comment by schwesig** [comment]
teams are set and organized. this boot strap issue is /closed.
Automation can be in focus again.
