### ISSUE TITLE
Open and release user personas work

### ISSUE THREAD

**Issue by quaid** [operate-first/community#150]
Review and release under project Open Source license:

- Matrix of user personas developed internally by Red Hat
- Covers all of the intended personas the project intends to focus on, now and in the future.

Note to reviewers @hpdempsey @bryanmontalvan @ghaff @jasonbrooks: when you feel the draft content is ready to publish externally, put a comment in this issue. We need 100% of reviewers with either a "+1" or a "+0" response to proceed with releasing. (This is just a prudent approach, rather than something prescribed.)

**Comment by quaid** [comment]
I went over the spreadsheet source material, and aside from one comment about a term uses, I think it's fine to release as-is.

**Comment by bryanmontalvan** [comment]
@quaid Sounds great!

**Comment by hpdempsey** [comment]
+1 as is

**Comment by jasonbrooks** [comment]
LGTM, I did make one comment in the ss

**Comment by bryanmontalvan** [comment]
+1

**Comment by quaid** [comment]
After the merge of #164, these are the user persona files to be created and then to migrate data into:

- Data Scientist
- Data Engineer
- Open Source Developer
- Academic Researcher
- Academic Administration
