### ISSUE TITLE
[op1st][WG Website] schedule these meetings in the public calendar

### ISSUE THREAD

**Issue by schwesig** [operate-first/community#157]
https://operatefirst.slack.com/archives/C036JDXAH0S/p1647878726981629?thread_ts=1647878688.713899&cid=C036JDXAH0S

**Comment by quaid** [comment]
OK, I have made a repeated calendar entry and invited @schwesig @hpdempsey @stefwrite @bryanmontalvan . If I've missed anyone, let me know. Folks can also pick up the event from the calendar entry itself.

Calendar ID:  operate.first.community@gmail.com
https://calendar.google.com/calendar/embed?src=operate.first.community%40gmail.com&ctz=America%2FLos_Angeles
https://calendar.google.com/calendar/ical/operate.first.community%40gmail.com/public/basic.ics

But I did not choose the time and date from PR #138 as it seems the timezone was put in as Eastern US, making it a recurring 05:30 meeting for me. Yet I don't want to delay momentum further by going back for a poll. We've got a few people interested in this work right now (I think I got you all correct above), so I picked a time that works tomorrow for everyone who is available. We can always move it in the future, if needed.
