### ISSUE TITLE
Create one or more quickstart guides for SRE/cloud operators/sysadmins

### ISSUE THREAD

**Issue by quaid** [operate-first/community#17]
It should provide a concise, new-user friendly set of instructions that gets someone productive immediately.

It should point to a subset of other documentation, with a brief description for each.

It can have a listing of all other documentation, but that may require too much maintenance.

Automating this part of the document of documents would be a good thing. It may that e.g. every document carries a specific 25 words-or-less description that is pulled into this document and parts of the website?

**Comment by quaid** [comment]
This is essentially the landing page when a viewer follows the SRE call to action on the front page.

The shape of this has become more clear, and might look like this:

- Intro & what you can do here
- Attend meetups, learn best practices from other SREs
- Learning Paths (tutorials, hands-on)
  - New to and interested in SRE
  - Experienced with SRE
  - Op1st community cloud specific path
  - Other specific SRE paths (NERC, etc.)
- Participation
  - Community of practice at OpenInfra Labs
  - Write SRE guides (in community of practice at OI Labs)
  - Perform SRE in an Operate First environment
- Contribute
  - Do SRE for operate-first.cloud
  - Assist other new projects with SRE/ops

**Comment by oindrillac** [comment]
cc: @4n4nd @HumairAK @tumido
