### ISSUE TITLE
Proposal: Form SIG Data Science

### ISSUE THREAD

**Issue by quaid** [operate-first/community#174]
This proposal is to evolve the Data Science Meetup community into being a special interest group with oversight for data science in Op1st across the board.

The mode would be to form as a SIG with a clear governance (chairs, meetings, etc.) for people interested in data science overall. Then the meetups continue as a subproject of the SIG, subprojects being the action points of SIGs where anyone can directly participate per guidelines.

There may already be activities, such as metrics, that could form as a subproject under SIG DS instead of forming as a stand-alone SIG.

I haven't really opened this discussion with any of the organizers of the meetup, so this issue is both me opening that discussion for the record, and following good process for proposing a SIG.

**Comment by MichaelClifford** [comment]
Hey @quaid, a DS SIG under OPF makes sense to me. And the OSG folks can help to get it started based on our current DS SIG governance. 

That said, I was wondering if we wanted to keep the existing meet up so DS focused when we move it over to new governance?  There are a lot of Operate First topics that we could discuss in this venue beyond our data science efforts (and I imagine we would not (at  least at this point) want to have a separate meetups per topic). Let me know what you think about eventually expanding the meet up from  "OPF DS Community meetup" to simply the "OPF Community meetup".  :smile: 

Also, other than, "metrics" and the meetup, are there any other initial ideas for the kinds of sub-projects/ working groups needed from an DS-SIG in OPF at the moment?

**Comment by aakankshaduggal** [comment]
@quaid - I agree with this as well. I think it's definitely a good step to have a DS SIG under operate first. 

And adding to @MichaelClifford's suggestion for expanding the meetup from "OPF DS Community meetup" to simply the "OPF Community meetup", I believe should be a good idea since we get a wider audience and this could help accelerate the process of building a community around the Operate First Cloud, referring to [O2KR2](https://docs.google.com/document/d/1XPAE_CFna-Y_BTThp-3AhSCneoVuTx9DRjToa3Fm3nA/edit#heading=h.uahno8r8ba3z).

**Comment by MichaelClifford** [comment]
I think the next steps for moving this item forward are the following: 

1) Find an additional member of the community outside of the OSG group to co-chair the DS SIG 

2) Draft a proposal to the OPF Community SIG to take over the operate first data science community meet up.

**Comment by MichaelClifford** [comment]
@quaid @aakankshaduggal Let me know if the above sounds good :)

**Comment by aakankshaduggal** [comment]
That sounds good @MichaelClifford, lmk if I can help with the proposal.

**Comment by MichaelClifford** [comment]
@quaid @aakankshaduggal I submitted a draft charter for a DS SIG here #193
