### ISSUE TITLE
Proposal: Form SIG Telemetry

### ISSUE THREAD

**Issue by quaid** [operate-first/community#175]
We accidentally skipped process for creating this SIG, so I'm creating this issue to do that process. Since it turns out we don't have a process, this issue also starts solving what needs to be in an issue template for creating a new SIG.

No big deal this happened because it was something in process from before the new governance, and I reckon it just slipped out minds that a discussion and process was still needed.

Relevant: #137 & #147 are the PRs where the process-less approvals occurred.

**Comment by quaid** [comment]
Noting that @RS1999ent isn't yet a member of the Op1st project on GitHub. Documentation for how to do that is here: https://github.com/operate-first/common/blob/main/docs/add_gh_member_and_access.md#become-a-github-member

**Comment by knikolla** [comment]
Me and @zaoxing are interested in rebooting this SIG, since it has been inactive for a while. @quaid can you point me to where the new governance processes for proposing SIGs are described?
