### ISSUE TITLE
Labels to change/create for this repo

### ISSUE THREAD

**Issue by quaid** [operate-first/community#2]
Not sure if we'll need the existing labels for issues, but I'm thinking we'll need ones that are specific to this repo. This issue is for listing the ideas for changes or new labels.

**Comment by goern** [comment]
hey there, any label is auto-created via https://github.com/thoth-station/thoth-application/blob/master/prow/overlays/cnv-prod/labels_operate-first.yaml either on an org-level or per-repo. Feel free to open a PR against that file.

**Comment by quaid** [comment]
OK, I've got my brain wrapped better around all this. I'm closing this issue. I do have the ability to manually create labels now, but I now see that I can see that Thoth can put some of my cross-repo relevant labels in other repos, so that is fantastic and I'll do the auto-creation process instead.
