### ISSUE TITLE
Moving Operate First DS Community repo to Operate First Org

### ISSUE THREAD

**Issue by aakankshaduggal** [operate-first/community#202]
As a part of moving the Operate First Data Science Community meetup from the OSG to the Operate First community SIG as discussed in https://github.com/operate-first/community/issues/192 

Hence, we would like to move the https://github.com/aicoe-aiops/operate-first-data-science-community to Operate First Organization. [These](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) are the steps we would be following to move the repository. To do the same, we would require access to the Operate First Organization or would need assistance from someone who has access and can help us with this. 

cc - @MichaelClifford, @quaid, @durandom

**Comment by durandom** [comment]
@schwesig can you please assist here?

**Comment by schwesig** [comment]
@aakankshaduggal let's have a quick call

**Comment by schwesig** [comment]
- [ ] adding schwesig to aicoe-aiops admin
- [ ] adding schwesig to operate-first admin
- [ ] moving repository

**Comment by schwesig** [comment]
Team access
@durandom what teams should have access?

- [ ] [admins](https://github.com/orgs/operate-first/teams/admins)
- [ ] [ai-for-cloud-ops](https://github.com/orgs/operate-first/teams/ai-for-cloud-ops)
- [ ] [Baristas](https://github.com/orgs/operate-first/teams/baristas)
- [ ] [blog](https://github.com/orgs/operate-first/teams/blog)
- [ ] [blog-editorial](https://github.com/orgs/operate-first/teams/blog-editorial)
- [ ] [blog-publishers](https://github.com/orgs/operate-first/teams/blog-publishers)
- [ ] [community-admins](https://github.com/orgs/operate-first/teams/community-admins)
- [ ] [Curator](https://github.com/orgs/operate-first/teams/curator)
- [ ] [custodians](https://github.com/orgs/operate-first/teams/custodians)
- [ ] [DevSecOps](https://github.com/orgs/operate-first/teams/devsecops)
- [ ] [ionos-openshift](https://github.com/orgs/operate-first/teams/ionos-openshift)
- [ ] [odh](https://github.com/orgs/operate-first/teams/odh)
- [ ] [operate-first-in-action](https://github.com/orgs/operate-first/teams/operate-first-in-action)
- [ ] [SourceOps](https://github.com/orgs/operate-first/teams/sourceops)
- [ ] [sre](https://github.com/orgs/operate-first/teams/sre)
- [ ] [sre-u](https://github.com/orgs/operate-first/teams/sre-u)
- [ ] [training](https://github.com/orgs/operate-first/teams/training)
- [ ] [triagers](https://github.com/orgs/operate-first/teams/triagers)
- [ ] [website](https://github.com/orgs/operate-first/teams/website)
- [ ] [workshoppers](https://github.com/orgs/operate-first/teams/workshoppers)

**Comment by schwesig** [comment]
moved the repo

**Comment by MichaelClifford** [comment]
@aakankshaduggal @schwesig Will this move break any of the links to https://old.operate-first.cloud/data-science/operate-first-data-science-community ?
