### ISSUE TITLE
Requirements for promoting an Operate First Workshop at DevConf

### ISSUE THREAD

**Issue by oindrillac** [operate-first/community#206]
Our proposal to run a [workshop on Operate First ](https://devconfus2022.sched.com/event/14eSx/build-aiops-tools-on-operate-first) that showcases ODH tools has been picked at DevConf.US August 2022.

The services and requirements per participant that we plan using and showcasing are:

**(Minimum)**
-  Jupyterlab (Small-Medium sized container images)
- S3 bucket (500mb-1GB)
- Kubeflow pipelines (2-4 step sequential pipeline  ~1 CPU 8 RAM each step)
- Openshift+Seldon 

**(Optional -Nice to have)**
- Trino (1-2 datasets)
- Superset (1 dashboard)

What is the setup that we can use for such a workshop? @HumairAK pointed out that smaug (+kubeflow pipelines) can accommodate this, as Smaug doesn't adhere to any SLA's/SLO's so uptime is not guaranteed, and we would need to have a plan B in case of an incident/downtime? 

**NOTE: the same workshop setup can also be re-used for a workshop on Operate First  at  the [SCALE](https://www.socallinuxexpo.org/scale/19x) conference in July.**

We can set 20-25 as the baseline that we can expect for the number of attendees.

cc: @HumairAK @durandom @aakankshaduggal @quaid

**Comment by durandom** [comment]
@oindrillac we should have workshops on the normal clusters, although they only have a community SLA. We can work on backup plans, like quickly bringing up an environment in AWS.

You should also be able to setup your own workshop environment in SMAUG and even in AWS. If not, let's work on documentation to do that.

**Comment by HumairAK** [comment]
> Jupyterlab (Small-Medium sized container images)

We should resolve the container sizes not showing up: https://github.com/operate-first/support/issues/599

**Comment by HumairAK** [comment]
> Shared S3 bucket 

We can use morty, but have a minio back up in place. We can also look into using aws s3 for this, looks like we're looking at around ~30GB, not sure what the costs of that look like.

**Comment by HumairAK** [comment]
> Users are able to view

We may want to consider putting an oauth proxy for the route, otherwise it will be public to all.

**Comment by HumairAK** [comment]
Furthers: https://github.com/open-services-group/scrum/issues/3

**Comment by oindrillac** [comment]
Workshop delivered at Scale19x
