### ISSUE TITLE
Dead Link: https://github.com/operate-first/community/blob/main/open-source-services.md

### ISSUE THREAD

**Issue by bexelbie** [operate-first/community#215]
https://github.com/operate-first/community/blob/main/open-source-services.md is not being rendered to the site resulting in dead links.

**Comment by stefwalter** [comment]
This link is now broken: https://www.operate-first.cloud/community/open-source-services.html 

It's linked everywhere on other websites, how can we get it back up?

**Comment by stefwalter** [comment]
@durandom How can I help get this link back up?

**Comment by durandom** [comment]
Dang. Somehow the `gh-pages` got disabled for this repo. I enabled it and we're back online.
Sorry for that.

**Comment by durandom** [comment]
and thanks @bexelbie for reporting that.

@schwesig @quaid we definitely need to get a better handle on watching all the issues in all those repos :)

**Comment by stefwalter** [comment]
Thanks. It's back up.

**Comment by schwesig** [comment]
> and thanks @bexelbie for reporting that.
> 
> @schwesig @quaid we definitely need to get a better handle on watching all the issues in all those repos :)

yes, we need to get better :-( thanks for linking and the feedback
