### ISSUE TITLE
Establish a process/tools for awareness of contribution metrics

### ISSUE THREAD

**Issue by quaid** [operate-first/community#22]
Create a tracking process and metrics tooling to go forward from this baseline. 

For inclusion tracking, be sure to breakdown the functional contribution areas. This helps ensure that clumps of e.g. only-Red-Hatters don’t get hidden in the tracking.

Document and track the ways the project is contributor-driven. This means, do contributors have access to all aspects of the project and the ability to have a seat at the decision making table for each aspect?

**Comment by quaid** [comment]
Open questions: 
- How do we know we are being successful attracting users?
- What ado we want our contributor base to look like?
- What are the range of first-order metrics we could be collecting?

**Comment by hemajv** [comment]
@Shreyanand and I are tracking some of these metrics in [this doc](https://docs.google.com/document/d/12JjCKzYzRBihR1cn6L0htp1yHQqZzKDEiQZCO7uz7qw/edit?usp=sharing) and we are also working on creating an initial notebook which fetched GitHub metrics from Augur to evaluate/visualize some of the metrics.

(Related issue: https://github.com/AICoE/data-driven-development/issues/4)

**Comment by hemajv** [comment]
Initial notebook exploring/visualizing some of the metrics: https://github.com/operate-first/community/blob/main/metrics/community_metrics.ipynb

**Comment by MichaelClifford** [comment]
/remove-lifecycle stale

@hemajv can this issue be closed? Or does it need more work from the O2KR2 two team? 

@schwesig
