### ISSUE TITLE
Create a project blog as the "Operate First official record"

### ISSUE THREAD

**Issue by quaid** [operate-first/community#24]
Create a project blog as a central point for short and long forms of project communications.

**Comment by schwesig** [comment]
Who can help, what best practice of a blog is. I am speaking in technical terms.
I would like to create a Red Hat and Operate First "respected" approach.

**Comment by quaid** [comment]
> Who can help, what best practice of a blog is. I am speaking in technical terms. I would like to create a Red Hat and Operate First "respected" approach. /cc @goern ?

Can you clarify what scope is covered by "technical"?

IME, the elements needed for a successful blog are:

1. A publication tool
2. A well-documented editorial workflow process
3. A formatting style guide
4. A language style guide
5. A way to schedule multiple similar/identical social media posts to specific outlets
6. An editorial calendar
7. Editors
8. Writers

For the publication tool, good features include:

- Self-service submission for review
- Easy to publish for blog poster approvers
- Memorable permalinks e.g. `blog.operate-first.cloud/2022/03/24/blogs-need-human-readable-permalinks`
- Ability to tag/categorize posts
- Way to show the author's byline/name
- Readers can filter by date, category, and author name
- Images can be shown inline with captions in blog posts

In the SIG Community meeting on 24  Mar we discussed how we think the writers we are recruiting now will be willing to work with a GitOps publication method.

In terms of what is out there already to work from:

1. A publication tool
   - @mscherer may have some bits we can look at. For te parts 
2. A well-documented editorial workflow process
3. A formatting style guide
4. A language style guide
   - These three I have parts we can work from
6. A way to schedule multiple similar/identical social media posts to specific outlets
   - This may exist or need to be created
7. An editorial calendar
   - Might be a flat file we can maintain?
8. Editors
   - I'm a fast editor, I can train others to do various parts of it
   - We need 1 editor for every 3 to 5 writers when things get flowing
9. Writers
   - Always the hardest part :)

**Comment by schwesig** [comment]
@quaid thanks for that detailed summary
technical: state of the art coded and published; secure, best open source, using our own methods (github process to publish), ...

**Comment by mscherer** [comment]
I do not have much to show, but I already wrote a few s2i image to take a hugo/zola repo and build deploy on Openshift. So that's as GitOps as possible, and I was planning on even get our future intern write a operator for that (so people can directly get the website repo as a parameter to the operator and everything is automatically built and updated)

**Comment by durandom** [comment]
I can work on the technical bits. The website is powered by [Gatsby ](https://www.gatsbyjs.com/) and can already post markdown with frontmatter.

@quaid can you work on a MVP for blog support? The list above looks like a full-fledged feature dump :)

**Comment by schwesig** [comment]
@durandom
My "first MVP" idea:

1. A publication tool
2. ~~A well-documented editorial~~ workflow process
3. ~~A formatting style guide~~
4. ~~A language style guide~~  --> a basic style guide
5. A way to schedule multiple similar/identical social media posts to specific outlets
6. An editorial calendar
7. ~~Editors~~
8. Writers

For the publication tool, good features include:

- ~~Self-service submission for review~~
- Easy to publish for blog poster approvers
- ~~Memorable permalinks e.g. blog.operate-first.cloud/2022/03/24/blogs-need-human-readable-permalinks~~
- Ability to tag/categorize posts
- ~~Way to show the author's byline/name~~
- Readers can filter by date, category, and author name
- ~~Images can be shown inline with captions in blog posts~~

**Comment by schwesig** [comment]
+1 starter-blog theme
+1 two pages as mentioned

**Comment by jeremyeder** [comment]
Checking in?

**Comment by quaid** [comment]
> Checking in?

I have this PR in review to create the repo:  https://github.com/operate-first/common/pull/95

Once it's created, I have the initial draft of the "idea to published"-process, sketches of a technical style markup guide, and a usable writing style guide. These will all form the core of the how-to for writers, reviewers, and editors.

I know @durandom is working on the tooling backend, which should also aiui go in this `blog` repo.

**Comment by durandom** [comment]
Habemus Blog

https://www.operate-first.cloud/blog/
https://github.com/operate-first/blog

**Comment by quaid** [comment]
@jeremyeder Now we need to have an editorial meeting :) Who do you want involved?

I'll start the PRs with my docs and processes into this new repo.

**Comment by quaid** [comment]
We decided to use the first blog posts being worked as a live demonstration and test of the editorial process.

https://github.com/operate-first/blog/pull/6
https://github.com/operate-first/blog/pull/7

We therefore have a project blog and this long-standing work item is complete!
