### ISSUE TITLE
Migration process for ROSA and NERC

### ISSUE THREAD

**Issue by rbadagandi** [operate-first/community#250]
# My question is:
Do we have a process documentation or reference point to understand the steps involved in migration?
How does one decide whether to opt for MOC or ROSA. Is there a cost involved with any of these? if yes who will bear it
How many cloud credits can we expect to be allocated for a project.
What happens when the credits are exhausted? 

# Additional information
My project Kruize HPO is on SMAUG cluster. What would be the impact of moving from SMAUG to MOC?

**Comment by quaid** [comment]
Thanks for your questions, I've added new answers to the FAQ and created a process document:

https://www.operate-first.cloud/community/community-cloud-faq.html#project-migration
https://www.operate-first.cloud/community/community-cloud-sunset-how-to.html
