### ISSUE TITLE
Common slidedeck presentation anyone can use for talks about Operate First

### ISSUE THREAD

**Issue by quaid** [operate-first/community#28]
Goal is to make it easier for project members to give talks of any kind about Operate First. These slides and demos can be pulled up on a laptop to show someone, or presented in a keynote at a conference.

This can be one set of "about the project" slides, which can be married to a set of "technical how-to" slides for that kind of audience. Finally, there can be a growing set of "presentation demos" that are maintained out of various managed services, so people can pick and choose what are most appropriate for their audiences.

**Comment by quaid** [comment]
Here is a list of potential audiences to keep in mind, knowing that the slides can be remixed for each context:

* Open source conferences
* Cloud-specific conferences
* Open source developers
* Anyone who is a cloud customer
* Any cloud software vendor

**Comment by billburnseh** [comment]
Adding Marcel. He did a deck intended to be a master deck where we could put all the slides, then we could extract what's needed for various uses. Would be a good starting point...

**Comment by durandom** [comment]
It's already in the shared drive[1]. But I think you're talking about creating a public version of it?
How about just moving that one to a personal google account? I don't think it has any confidential slides...

[1] https://docs.google.com/presentation/d/12m5fF4j2Gr_Fj4Gbq7t8M_fsjYILm1PBM1EXJ_El3Uw

**Comment by quaid** [comment]
> It's already in the shared drive[1]. But I think you're talking about creating a public version of it?
> How about just moving that one to a personal google account? I don't think it has any confidential slides...
> 
> [1] https://docs.google.com/presentation/d/12m5fF4j2Gr_Fj4Gbq7t8M_fsjYILm1PBM1EXJ_El3Uw

Yeah, that's a great starting point. I know we can just externalize it, but for incorporating it into the community workflow, how about this:

1. Convert the slides to Markdown and ReactJS
2. Brand the slides for Operate First
3. Curate an initial 12-15 slides that tell the core story, get those up front
4. Have a divider for "additional material", with useful but not always needed slides put in there
5. When anyone uses the deck, they can fork and remix for their own purposes.
6. If they have a new slide or changes, they can submit them via PR, where the rest of us can review before inclusion in the main set of slides.

**Comment by quaid** [comment]
> It's already in the shared drive[1]. But I think you're talking about creating a public version of it?
> How about just moving that one to a personal google account? I don't think it has any confidential slides...
> 
> [1] https://docs.google.com/presentation/d/12m5fF4j2Gr_Fj4Gbq7t8M_fsjYILm1PBM1EXJ_El3Uw

Yeah, that's a great starting point. I know we can just externalize it, but for incorporating it into the community workflow, how about this:

1. Convert the slides to Markdown and ReactJS
2. Brand the slides for Operate First
3. Curate an initial 12-15 slides that tell the core story, get those up front
4. Have a divider for "additional material", with useful but not always needed slides put in there
5. When anyone uses the deck, they can fork and remix for their own purposes.
6. If they have a new slide or changes, they can submit them via PR, where the rest of us can review before inclusion in the main set of slides.


> > It's already in the shared drive[1]. But I think you're talking about creating a public version of it?
> > How about just moving that one to a personal google account? I don't think it has any confidential slides...
> > [1] https://docs.google.com/presentation/d/12m5fF4j2Gr_Fj4Gbq7t8M_fsjYILm1PBM1EXJ_El3Uw
> 
> Yeah, that's a great starting point. I know we can just externalize it, but for incorporating it into the community workflow, how about this:
> 
>     1. Convert the slides to Markdown and ReactJS
> 
>     2. Brand the slides for Operate First
> 
>     3. Curate an initial 12-15 slides that tell the core story, get those up front
> 
>     4. Have a divider for "additional material", with useful but not always needed slides put in there
> 
>     5. When anyone uses the deck, they can fork and remix for their own purposes.
> 
>     6. If they have a new slide or changes, they can submit them via PR, where the rest of us can review before inclusion in the main set of slides.

I've been thinking about this and wanted to note:  we lose a lot of easy collaboration and remixing experience if we move it out of Google Slides. But we don't have a community-focused Google Workspace to share from. And ultimately, each piece of non-open infrastructure we rely upon for core functions is something we want to track on the "FIXME Roadmap."

**Comment by billburnseh** [comment]
+1 on this idea.
