### ISSUE TITLE
Figure out full site information architecture

### ISSUE THREAD

**Issue by quaid** [operate-first/community#40]
Full site tree and information relationship

**Comment by oindrillac** [comment]
just from a site tree perspective, you can get the current structure from the configs in https://github.com/operate-first/operate-first.github.io/tree/master/config, this does not include anything from an information perspective, so an information index could be helpful

**Comment by quaid** [comment]
We took this back to work on in a Google Doc, to help with the rapid review/approval process. Here is the read-only publish of that doc:

https://docs.google.com/document/d/e/2PACX-1vSTR7gBEMnfWMSNVg8AqcCnxfLtpYqCgelpB1KzYnifrq7HIDSIl89OEPpLOn_YSF87Y7hquzy0AOY1/pub

Attached here is a the latest diagram from discussions today.

![website-information-achitecture](https://user-images.githubusercontent.com/112760/126264616-90f023ee-411a-4a60-9561-013c03430082.png)

**Comment by quaid** [comment]
Action: Website Updates WG to have discussion about menu changes here
@schwesig @bryanmontalvan @stefwrite @quaid

**Comment by quaid** [comment]
#103 is relevant and somewhat redundant

**Comment by quaid** [comment]
We have our new architecture in place and can review any proposed future changes under a new PR/Issue.

Summary:

- New top level menu with a handful of pages: Purpose, Community, Blog, Docs & Training, Community Cloud
- Can add individual pages, when needed, but for now we have the desired site architecture.
- All subprojects, WGs, and SIGs maintain their sections as Jupyter Notebooks.

/close
