### ISSUE TITLE
Auth options for lists.operate-first.cloud

### ISSUE THREAD

**Issue by quaid** [operate-first/community#77]
In #53 we discussed some third-party authentication methods to help our users reduce their user-account-loud. That is, in addition to native Mailman 3 authentication, we could add types such as:

1. GitHub auth
2. Google auth
3. Op1st community SSO

The Op1st community SSO solution is preferred, if we're only going to have one in addition to the native auth.

However, having multiple reasonable options would give people choice, with 'reasonable' meaning we keep the list to just the three above and `0. Native authentication` so it's not too many to implement, maintain, and face like a too-large food menu.

**Comment by mscherer** [comment]
So it seems I got the auth stack wrong, Mailman use django-allauth, not django-socialauth. Django-allauth has keycloack:
https://django-allauth.readthedocs.io/en/latest/providers.html#keycloak

**Comment by mscherer** [comment]
But we have the version 0.34, and this feature requires 0.42:
https://github.com/pennersr/django-allauth/commit/54959b664bfc93c8d37b0aaccb550b05f1c160f7 

0.34 has openid, oauth and oauth2, so keycloak should work too using those. A quick read of the code show this is just a wrapper around oauth2 module, so I can either backport that code, or see how we can use oauth2.

**Comment by tumido** [comment]
Operate First SSO _is_ Keycloak and uses Github social auth as IDP.

If you give me the OIDC redirect url for the Mailman, I can set it up on the keycloak side.

**Comment by quaid** [comment]
> Yeah, but the module we use (django-allauth) is not supporting keycloack as a direct option (direct option which is just a wrapper preconfigured with the others supported auth systems). I am a bit rusty on openid vs openid connect vs oauth vs oauth2, so I will need to read a bit before I can answer to your request.

@mscherer have you had a chance to look at this? Is this underlying what is blocking operate-first/apps#942 ?

**Comment by mscherer** [comment]
I totally forgot, sorry. I will take a look tomorrow, but yes, that's likely what is blocking.

**Comment by mscherer** [comment]
So I think the OIDC redirect would be: 
```
https://lists.operate-first.cloud/accounts/keycloak/login/callback/
```

if I am not wrong. I need the realm and the url (cause I am quite sure that "example.org" is not the right URI, and "gondor" is not the answer for "realm").

**Comment by quaid** [comment]
> So I think the OIDC redirect would be:
> 
> ```
> https://lists.operate-first.cloud/accounts/keycloak/login/callback/
> ```
> 
> if I am not wrong. I need the realm and the url (cause I am quite sure that "example.org" is not the right URI, and "gondor" is not the answer for "realm").

@tumido ^^^
