### ISSUE TITLE
Adding reviewnb to the repo

### ISSUE THREAD

**Issue by cdolfi** [operate-first/community#81]
Reviewing notebooks can be made a lot easier by having reviewnb on the repo. I would like to make more pointed review comments on #80 with this tool

**Comment by MichaelClifford** [comment]
Did reviewnb ever get installed for the operate-first org?

**Comment by MichaelClifford** [comment]
/remove-lifecycle stale

Did an Operate First Org Admin ever install [ReviewNB](https://www.reviewnb.com/) in the Operate First Org?

**Comment by harshad16** [comment]
[Opf Admin](https://github.com/operate-first/common/blob/main/github-config.yaml#L3-L9) has to install the github app https://github.com/marketplace/review-notebook-app onto the repo.

**Comment by harshad16** [comment]
@schwesig  i think the following way can be used to check this:
- View the `setting > GitHub app ` on the repo, and check if the app is in that list.
- Verify its functioning by opening a PR with jupyter notebook file `.ipynb` , in the pr review the app would function.
