### ISSUE TITLE
Demo JupyterBook as all-in-one course tool

### ISSUE THREAD

**Issue by quaid** [operate-first/community#85]
After seeing a recent demo by a BU professor, I would like us to demo similar capabilities for Op1st learning pathways. The audience for this demo is the team working on SRE training. The demo can use existing Op1st training materials for Data Science; let's pick something that fits nicely into the AIOps needs of an SRE.

If @isabelizimm is available, that would be great—we discussed this briefly following that demo.

The demo could cover:
1. Showing course lecture notes from instructor & student POV.
2. Students being able to live-launch into a working environment for the lecture (JupyterHub, or ssh into a dev shell, or ...)
3. The workflow from the content creator/instructor perspective.

I know that the full features we'd want may not be straightforward to implement or feature-ready. I think we can consider a few parts with waving-hands-effects, "And here it would launch you into JuypterHub, like this screenshot."

**Comment by MichaelClifford** [comment]
@quaid Would something like this meet the needs for your demo? https://isabelizimm.github.io/ocp-ci-analysis/README.html 

It's still in a [PR](https://github.com/aicoe-aiops/ocp-ci-analysis/pull/383) but should be mereged shortly.

**Comment by isabelizimm** [comment]
I'd love to help show it off! I think the AI-4-CI repo linked above would work well as a deployed case, or  https://github.com/aicoe-aiops/meteor-demo, which is a minimal Jupyter Book for showing off capabilities.

**Comment by quaid** [comment]
We got the main purpose of this done with this Red Hat Research talk:  https://youtu.be/EEnk9PSIoSI

I'm going to make a new issue about doing a highlights reel from that one.
