### ISSUE TITLE
Define an SLE-driven model for community production clouds

### ISSUE THREAD

**Issue by quaid** [operate-first/community#88]
We can adopt SLOs for our community production cloud, but it can't role into an SLA. The SLA model is the wrong encapsulation of the relationship between members of a community. By it's nature, an SLA is a form of contract (Agreement), and even when it's not monetary but e.g. an employment contract such that if a person fails to meet internal SLAs, the consequences are governed by their employment contract. This is how teams internal to an org can have SLAs between them. So the relationships are always transactional.

A community on the other hand is non-transactional (or if it is, it's toxic and to be avoided.) Using an SLA is a non-starter. There is a different concept, seemingly started at Carnegie-Mellon University, which I've seen e.g. [adopted by Community Platform Engineering (CPE) team](https://docs.fedoraproject.org/en-US/cpe/sle_services/) who run infrastructure for Fedora and CentOS: SLEs

The Service Level Expectation is about a communal understanding of what is expected, and what the response is if something falls short of that expectation.

I've also begun to read about Service Level Experience, which centers it more on the whole user experience. I'm not sure of the relationship as understood by creators and users of these terms. It seems to me we have flexibility to adjust meaning to our purpose.

Some questions then are:
- Can we measure SLE?
- Can we define SLOs for an expectation or an experience?
- If yes, what are the risks/rewards to having SLEs for open source services, letting us run a proper SRE environment with error budgets, etc.

So an open source project can decide to have a reduced quality user experience if they want to push releases more quickly (lower the SLOs based on the adjusted SLE), that's all within their control.

But if they choose to assure their users of a better experience, then the developers will have incentive to set a high SLE and keep under error budget. Because they've agreed _socially_ to not push a release without error budget, and they want to be good community members with the SRE team.

We could use some SRE theoreticians with open source community experience to help create an initial usable model.

What do you think?

I understand our open source dev users aren't necessarily coming for a full SRE experience. The idea here is to get everyone used to respecting error budgets and SLOs from the very start, while supporting the sustainability of the open source SRE team in being able to scale projects in a reasonable manner.

**Comment by billburnseh** [comment]
Nit, first sentence, replace role with roll...

**Comment by Gregory-Pereira** [comment]
@quaid, anything else to add to this? Should this discussion remain open?
/remove-lifecycle stale

**Comment by quaid** [comment]
Yes thanks @Gregory-Pereira this is an ongoing effort
