### ISSUE TITLE
New mailing list on `lists.operate-first.cloud` for DS community meetup 

### ISSUE THREAD

**Issue by MichaelClifford** [operate-first/community#91]
I would like to add a new mailing list to the `lists.operate-first.cloud` that aims to provide updates and communication for the operate first data science community and their associated meet up. What is the best way to go about getting this new list made, and volunteering to manage it? Let me know, thanks!

**Comment by quaid** [comment]
> I would like to add a new mailing list to the `lists.operate-first.cloud` that aims to provide updates and communication for the operate first data science community and their associated meet up. What is the best way to go about getting this new list made, and volunteering to manage it? Let me know, thanks!

We need to create an issue template for this ultimately, let's start by asking/answering all the questions here that a template would solve.

1. What is the list address name? foo@
2. Short description of list
3. One- or two-sentence list description/more information
3. Display name and subject prefix, i.e., Community & [Community]
4. Archives are required to be public and subscription open, with the exception of e.g. security@-type mailing lists
5. Subscription policy:
    - Open: Subscriptions are added automatically
    - Confirm: Subscribers need to confirm the subscription using an email sent to them
    - Moderate: Moderators will have to authorize each subscription manually.
    - Confirm then Moderate: First subscribers have to confirm, then a moderator needs to authorize.

**Comment by MichaelClifford** [comment]
> 1. What is the list address name? foo@

data-science@ 

>2. Short description of list  

Provides updates and communication for the operate first data science community and their associated meet up

>3. Display name and subject prefix, i.e., Community & [Community]

Data Science [Data Science]

>4. Archives are required to be public and subscription open, with the exception of e.g. security@-type mailing lists

Ok

> 5. Subscription policy

Open

**Comment by quaid** [comment]
> data-science@
> 
> > 1. Short description of list
> 
> Provides updates and communication for the operate first data science community and their associated meet up

Is there any reason we can't use community@lists.operate-first.cloud for these topics and discussions?

A good practice is to keep _all_ community activities on one central list until it's clear that a new list is needed. In the case of the Operate First community, we aren't using our current list yet very much. It could really use the updates, communication, and meetup information, all of which are of general interest too.

An exception to that practice is often made for announce lists that are topical. Then of course, there are infinite specific reasons why a new discussion list is needed, many of which make sense in our context. But my recommendation in general is to keep all community discussions in one place so we're all included, unless doing so risks exclusion in another way. (For example, you might feel data scientists won't join or speak up on the community@ list but will do so in a space clearly marked for Data Science? Which is definitely worth discussing, as this may the solution, or there may another one that we'd all prefer.)

**Comment by MichaelClifford** [comment]
@quaid If using the current community list is your recommendation that is fine with me :smile: I wasn't sure exactly what the overall purpose of that list was, and did not want to hijack it for our meet up.   

I think your suggestion makes a lot of sense. We will use the "community" list as our primary communication channel for now. If down the road we feel a separate list is need/justified we can re-assess. 

Thanks!
