### ISSUE TITLE
{Meeting} Project Coordination Meeting

### ISSUE THREAD

**Issue by schwesig** [operate-first/community#96]
_First Idea/Draw how to make meetings visible_

### Topic/Title
Project Coordination Meeting

### Content
... link to notes/agenda/protocol/recordings

### Goals/Purpose
The purpose of this meeting is to provide a forum to discuss topics related to the introduction of new
projects and workloads to the original operate first community cloud (with resources at the Mass Open Cloud, Hetzner and beyond).

### Frequency/Time
bi-weekly, Wednesday, 8:30 am EST

### Length
60minutes

### Audience
All are welcome

### Host
@billburnseh

### Platform
Google Meet, recorded

### example Agenda

- Meetings
- Introductions
- - New People/New Projects
- Topics
- - Status of the community cloud
- - Data and legal usage topics
- - Status of wider ops team (MOC/NERC ops folks with Op1St team)
- New projects onboarded / onboarding / planned / possible

**Comment by billburnseh** [comment]
That is about right. Typically less than 60 minutes though. While it was intended to introduce folks bringing new projects, that has gotten rare, esp where the web content tells them how to directly connect to the Ops team. Most of the meeting tends to be status updates and such.  I would recommend scrapping this meeting, with the Ops team handling welcoming and onboarding new projects as they see fit. I think the remaining content would fit better into a new program meeting.

**Comment by billburnseh** [comment]
FYI, the project coordination meeting has been suspended with the the Jan 12, 2022 meeting.
